In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('data/train.csv')

In [22]:
df.head()

,student_id,application_year,age,graduation_year,department,university_tier,cgpa,english_exam_score,attendance_rate,failed_courses_count,...,leadership_score,presentation_score,certification_count,bootcamp_count,applications_sent,interviews_attended,hobby,preferred_social_media_platform,career_success_score,mentor_feedback_text
0,STU_000001,2021,21,2021,Computer Engineering,Tier 4,3.17,62.54,77.31,0,...,62.70,58.84,3,1,24,0,photography,LinkedIn,86.78,Proje kalitesi ve makine öğrenimi konusundaki ...
1,STU_000002,2024,20,2024,Computer Engineering,Tier 4,3.24,75.10,87.13,3,...,42.32,40.54,2,0,46,5,reading,YouTube,46.16,Kodlama ve problem çözme becerileri gelişmekte...
2,STU_000003,2024,28,2024,Electrical Electronics Engineering,Tier 4,3.00,68.53,95.64,1,...,47.27,82.56,1,2,46,5,cinema,Reddit,84.08,İleri düzey frontend geliştirme becerileri ile...
3,STU_000004,2019,22,2018,Computer Engineering,Tier 1,2.82,54.85,77.80,2,...,78.69,85.05,2,4,49,7,running,Reddit,89.97,Güçlü bir kodlama yeteneği ve backend geliştir...
4,STU_000005,2026,22,2026,Computer Engineering,Tier 3,2.28,72.25,71.97,1,...,27.22,84.29,1,0,119,13,football,X,92.46,Ürün analizi alanına olan tutkusu ve makine öğ...

In [23]:
df.isnull().sum()

student_id                            0
application_year                      0
age                                   0
graduation_year                       0
department                            0
university_tier                       0
cgpa                                  0
english_exam_score                  953
attendance_rate                       0
failed_courses_count                  0
target_role                           0
coding_score                          0
problem_solving_score                 0
data_structures_score                 0
sql_score                             0
machine_learning_score                0
backend_score                         0
frontend_score                        0
cloud_score                           0
devops_score                          0
project_quality_score                 0
real_client_project_count             0
internship_count                      0
internship_duration_months         1657
freelance_project_count               0
hackathon_count                       0
hackathon_awards                      0
portfolio_score                     364
github_repo_count                     0
github_avg_stars                    910
open_source_contribution_count      910
linkedin_profile_score              668
cv_quality_score                      0
technical_interview_score             0
hr_interview_score                  780
communication_score                   0
teamwork_score                        0
leadership_score                      0
presentation_score                    0
certification_count                   0
bootcamp_count                        0
applications_sent                     0
interviews_attended                   0
hobby                                 0
preferred_social_media_platform       0
career_success_score                  0
mentor_feedback_text                  0
dtype: int64

In [24]:
df.dtypes

student_id                          object
application_year                     int64
age                                  int64
graduation_year                      int64
department                          object
university_tier                     object
cgpa                               float64
english_exam_score                 float64
attendance_rate                    float64
failed_courses_count                 int64
target_role                         object
coding_score                       float64
problem_solving_score              float64
data_structures_score              float64
sql_score                          float64
machine_learning_score             float64
backend_score                      float64
frontend_score                     float64
cloud_score                        float64
devops_score                       float64
project_quality_score              float64
real_client_project_count            int64
internship_count                     int64
internship_duration_months         float64
freelance_project_count              int64
hackathon_count                      int64
hackathon_awards                     int64
portfolio_score                    float64
github_repo_count                    int64
github_avg_stars                   float64
open_source_contribution_count     float64
linkedin_profile_score             float64
cv_quality_score                   float64
technical_interview_score          float64
hr_interview_score                 float64
communication_score                float64
teamwork_score                     float64
leadership_score                   float64
presentation_score                 float64
certification_count                  int64
bootcamp_count                       int64
applications_sent                    int64
interviews_attended                  int64
hobby                               object
preferred_social_media_platform     object
career_success_score               float64
mentor_feedback_text                object
dtype: object

In [25]:
df["department"].value_counts()

department
Computer Engineering                  2961
Software Engineering                  2212
Electrical Electronics Engineering    1850
Industrial Engineering                 806
Statistics                             802
Management Information Systems         769
Mathematics                            600
Name: count, dtype: int64

In [26]:
df["target_role"].value_counts()

target_role
Backend Developer        1769
Software Developer       1572
Frontend Developer       1312
Data Scientist           1229
Data Analyst             1156
Cloud Engineer            838
AI Engineer               827
DevOps Engineer           525
Cybersecurity Analyst     438
MLOps Engineer            223
Product Analyst           111
Name: count, dtype: int64

In [27]:
# Fill the missing values in the 'english_exam_score' column with the mean of the column
df["english_exam_score"] = df["english_exam_score"].fillna(df["english_exam_score"].mean())

In [28]:
# Fill the missing values in the 'internship_duration_months' column with the median of the column for each 'internship_count' group
df['internship_duration_months'] = df.groupby('internship_count')['internship_duration_months'].transform(
    lambda x: x.fillna(x.median())
)

In [29]:
df

,student_id,application_year,age,graduation_year,department,university_tier,cgpa,english_exam_score,attendance_rate,failed_courses_count,...,leadership_score,presentation_score,certification_count,bootcamp_count,applications_sent,interviews_attended,hobby,preferred_social_media_platform,career_success_score,mentor_feedback_text
0,STU_000001,2021,21,2021,Computer Engineering,Tier 4,3.17,62.540000,77.31,0,...,62.70,58.84,3,1,24,0,photography,LinkedIn,86.78,Proje kalitesi ve makine öğrenimi konusundaki ...
1,STU_000002,2024,20,2024,Computer Engineering,Tier 4,3.24,75.100000,87.13,3,...,42.32,40.54,2,0,46,5,reading,YouTube,46.16,Kodlama ve problem çözme becerileri gelişmekte...
2,STU_000003,2024,28,2024,Electrical Electronics Engineering,Tier 4,3.00,68.530000,95.64,1,...,47.27,82.56,1,2,46,5,cinema,Reddit,84.08,İleri düzey frontend geliştirme becerileri ile...
3,STU_000004,2019,22,2018,Computer Engineering,Tier 1,2.82,54.850000,77.80,2,...,78.69,85.05,2,4,49,7,running,Reddit,89.97,Güçlü bir kodlama yeteneği ve backend geliştir...
4,STU_000005,2026,22,2026,Computer Engineering,Tier 3,2.28,72.250000,71.97,1,...,27.22,84.29,1,0,119,13,football,X,92.46,Ürün analizi alanına olan tutkusu ve makine öğ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,STU_009996,2019,21,2019,Mathematics,Tier 2,3.46,66.270000,84.95,3,...,61.97,36.35,1,3,53,7,football,TikTok,72.99,Proje çalışmalarında genel olarak tutkulu bir ...
9996,STU_009997,2026,24,2025,Industrial Engineering,Tier 2,2.68,57.372187,79.56,0,...,55.50,64.57,1,2,7,0,running,Instagram,100.00,Mükemmel bir kariyer başarısı elde eden öğrenc...
9997,STU_009998,2023,20,2023,Electrical Electronics Engineering,Tier 3,3.55,32.900000,88.34,1,...,25.83,55.16,1,1,124,11,gaming,Reddit,65.13,Veri bilimi alanında kendine güvenen bir öğren...
9998,STU_009999,2022,24,2022,Computer Engineering,Tier 3,2.73,57.372187,91.60,0,...,32.24,64.59,0,1,39,3,reading,YouTube,100.00,Veri analitiği alanındaki çalışmalarıyla dikka...
9999,STU_010000,2025,22,2025,Electrical Electronics Engineering,Tier 3,3.11,58.110000,79.95,0,...,73.98,32.42,3,1,67,9,football,Instagram,73.92,Bulut mühendisliği hedefiyle yola çıkan öğrenc...

In [30]:
# Fill the missing values in the 'linkedin_profile_score' column with the mean of the column
df["linkedin_profile_score"] = df["linkedin_profile_score"].fillna(
    df["linkedin_profile_score"].mean()
)

In [31]:
# Fill the missing values in the 'hr_interview_score' column with the mean of the column
df["hr_interview_score"] = df["hr_interview_score"].fillna(
    df["hr_interview_score"].mean()
)

In [32]:
# Fill the missing values in the 'portfolio_score' column with the mean of the column
df['portfolio_score'] = df['portfolio_score'].fillna(
    df['portfolio_score'].mean()
    )

In [33]:
# Fill the missing values in the 'github_avg_stars' column with the median of the column
df["github_avg_stars"]= df["github_avg_stars"].fillna(df["github_avg_stars"].median())

# Fill the missing values in the 'open_source_contribution_count' column with the median of the column
df["open_source_contribution_count"] = df["open_source_contribution_count"].fillna(
    df["open_source_contribution_count"].median())

In [34]:
df.isnull().sum()

student_id                         0
application_year                   0
age                                0
graduation_year                    0
department                         0
university_tier                    0
cgpa                               0
english_exam_score                 0
attendance_rate                    0
failed_courses_count               0
target_role                        0
coding_score                       0
problem_solving_score              0
data_structures_score              0
sql_score                          0
machine_learning_score             0
backend_score                      0
frontend_score                     0
cloud_score                        0
devops_score                       0
project_quality_score              0
real_client_project_count          0
internship_count                   0
internship_duration_months         0
freelance_project_count            0
hackathon_count                    0
hackathon_awards                   0
portfolio_score                    0
github_repo_count                  0
github_avg_stars                   0
open_source_contribution_count     0
linkedin_profile_score             0
cv_quality_score                   0
technical_interview_score          0
hr_interview_score                 0
communication_score                0
teamwork_score                     0
leadership_score                   0
presentation_score                 0
certification_count                0
bootcamp_count                     0
applications_sent                  0
interviews_attended                0
hobby                              0
preferred_social_media_platform    0
career_success_score               0
mentor_feedback_text               0
dtype: int64

In [35]:
df.shape

(10000, 47)

In [36]:
from sklearn.preprocessing import LabelEncoder

object_cols = df.select_dtypes(include="object").columns
object_cols = [col for col in object_cols if col != "student_id"]

le = LabelEncoder()

for col in object_cols:
    df[col] = le.fit_transform(df[col])

In [37]:
df.dtypes

student_id                          object
application_year                     int64
age                                  int64
graduation_year                      int64
department                           int32
university_tier                      int32
cgpa                               float64
english_exam_score                 float64
attendance_rate                    float64
failed_courses_count                 int64
target_role                          int32
coding_score                       float64
problem_solving_score              float64
data_structures_score              float64
sql_score                          float64
machine_learning_score             float64
backend_score                      float64
frontend_score                     float64
cloud_score                        float64
devops_score                       float64
project_quality_score              float64
real_client_project_count            int64
internship_count                     int64
internship_duration_months         float64
freelance_project_count              int64
hackathon_count                      int64
hackathon_awards                     int64
portfolio_score                    float64
github_repo_count                    int64
github_avg_stars                   float64
open_source_contribution_count     float64
linkedin_profile_score             float64
cv_quality_score                   float64
technical_interview_score          float64
hr_interview_score                 float64
communication_score                float64
teamwork_score                     float64
leadership_score                   float64
presentation_score                 float64
certification_count                  int64
bootcamp_count                       int64
applications_sent                    int64
interviews_attended                  int64
hobby                                int32
preferred_social_media_platform      int32
career_success_score               float64
mentor_feedback_text                 int32
dtype: object

In [ ]:
# df.to_csv('data/train_preprocessed.csv', index=False)

## Feature Selection

In [19]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LassoCV

In [20]:
x = df.drop(columns=["student_id", "mentor_feedback_text", "career_success_score"])
y = df["career_success_score"]

In [21]:
lasso = LassoCV(cv=5, random_state=42)
lasso.fit(x, y)

LassoCV(cv=5, random_state=42)

In [22]:
feature_importance = pd.Series(lasso.coef_, index=x.columns)
feature_importance.sort_values(ascending=False, inplace=True)
print(feature_importance)

real_client_project_count          1.382629
cgpa                               1.360617
hackathon_awards                   0.732441
project_quality_score              0.326667
hackathon_count                    0.310188
github_repo_count                  0.229668
internship_duration_months         0.223326
technical_interview_score          0.205924
bootcamp_count                     0.179466
certification_count                0.177395
communication_score                0.113342
problem_solving_score              0.096121
interviews_attended                0.095083
portfolio_score                    0.088585
cloud_score                        0.085719
teamwork_score                     0.062951
coding_score                       0.061098
github_avg_stars                   0.059952
devops_score                       0.058002
cv_quality_score                   0.055281
open_source_contribution_count     0.046485
backend_score                      0.038990
hr_interview_score                 0.038038
presentation_score                 0.035563
linkedin_profile_score             0.033971
leadership_score                   0.025962
attendance_rate                    0.024359
english_exam_score                 0.020294
sql_score                          0.014587
machine_learning_score             0.011097
applications_sent                  0.005642
hobby                              0.000000
preferred_social_media_platform   -0.000000
freelance_project_count            0.000000
age                                0.000000
internship_count                  -0.000000
frontend_score                     0.000000
department                         0.000000
data_structures_score             -0.003413
graduation_year                   -0.198375
target_role                       -0.289427
application_year                  -0.319979
failed_courses_count              -0.615147
university_tier                   -1.140868
dtype: float64

# Test dataset process

In [39]:
test_df = pd.read_csv('data/test_x.csv')

In [24]:
student_id = test_df["student_id"]

In [40]:
test_df.dtypes

student_id                          object
application_year                     int64
age                                  int64
graduation_year                      int64
department                          object
university_tier                     object
cgpa                               float64
english_exam_score                 float64
attendance_rate                    float64
failed_courses_count                 int64
target_role                         object
coding_score                       float64
problem_solving_score              float64
data_structures_score              float64
sql_score                          float64
machine_learning_score             float64
backend_score                      float64
frontend_score                     float64
cloud_score                        float64
devops_score                       float64
project_quality_score              float64
real_client_project_count            int64
internship_count                     int64
internship_duration_months         float64
freelance_project_count              int64
hackathon_count                      int64
hackathon_awards                     int64
portfolio_score                    float64
github_repo_count                    int64
github_avg_stars                   float64
open_source_contribution_count     float64
linkedin_profile_score             float64
cv_quality_score                   float64
technical_interview_score          float64
hr_interview_score                 float64
communication_score                float64
teamwork_score                     float64
leadership_score                   float64
presentation_score                 float64
certification_count                  int64
bootcamp_count                       int64
applications_sent                    int64
interviews_attended                  int64
hobby                               object
preferred_social_media_platform     object
mentor_feedback_text                object
dtype: object

In [41]:
from sklearn.preprocessing import LabelEncoder

object_cols = test_df.select_dtypes(include="object").columns
object_cols = [col for col in object_cols if col != "student_id"]

le = LabelEncoder()

for col in object_cols:
    test_df[col] = le.fit_transform(test_df[col])

In [42]:
test_df.dtypes

student_id                          object
application_year                     int64
age                                  int64
graduation_year                      int64
department                           int32
university_tier                      int32
cgpa                               float64
english_exam_score                 float64
attendance_rate                    float64
failed_courses_count                 int64
target_role                          int32
coding_score                       float64
problem_solving_score              float64
data_structures_score              float64
sql_score                          float64
machine_learning_score             float64
backend_score                      float64
frontend_score                     float64
cloud_score                        float64
devops_score                       float64
project_quality_score              float64
real_client_project_count            int64
internship_count                     int64
internship_duration_months         float64
freelance_project_count              int64
hackathon_count                      int64
hackathon_awards                     int64
portfolio_score                    float64
github_repo_count                    int64
github_avg_stars                   float64
open_source_contribution_count     float64
linkedin_profile_score             float64
cv_quality_score                   float64
technical_interview_score          float64
hr_interview_score                 float64
communication_score                float64
teamwork_score                     float64
leadership_score                   float64
presentation_score                 float64
certification_count                  int64
bootcamp_count                       int64
applications_sent                    int64
interviews_attended                  int64
hobby                                int32
preferred_social_media_platform      int32
mentor_feedback_text                 int32
dtype: object

In [43]:
test_df.isnull().sum()

student_id                            0
application_year                      0
age                                   0
graduation_year                       0
department                            0
university_tier                       0
cgpa                                  0
english_exam_score                  944
attendance_rate                       0
failed_courses_count                  0
target_role                           0
coding_score                          0
problem_solving_score                 0
data_structures_score                 0
sql_score                             0
machine_learning_score                0
backend_score                         0
frontend_score                        0
cloud_score                           0
devops_score                          0
project_quality_score                 0
real_client_project_count             0
internship_count                      0
internship_duration_months         1586
freelance_project_count               0
hackathon_count                       0
hackathon_awards                      0
portfolio_score                     382
github_repo_count                     0
github_avg_stars                    895
open_source_contribution_count      895
linkedin_profile_score              680
cv_quality_score                      0
technical_interview_score             0
hr_interview_score                  759
communication_score                   0
teamwork_score                        0
leadership_score                      0
presentation_score                    0
certification_count                   0
bootcamp_count                        0
applications_sent                     0
interviews_attended                   0
hobby                                 0
preferred_social_media_platform       0
mentor_feedback_text                  0
dtype: int64

In [44]:
test_df.shape

(10000, 46)

In [45]:
# Fill the missing values in the 'english_exam_score' column with the mean of the column
test_df["english_exam_score"] = test_df["english_exam_score"].fillna(test_df["english_exam_score"].mean())

In [46]:
# Fill the missing values in the 'internship_duration_months' column with the median of the column for each 'internship_count' group
test_df['internship_duration_months'] = test_df.groupby('internship_count')['internship_duration_months'].transform(
    lambda x: x.fillna(x.median())
)

In [47]:
# Fill the missing values in the 'linkedin_profile_score' column with the mean of the column
test_df["linkedin_profile_score"] = test_df["linkedin_profile_score"].fillna(
    test_df["linkedin_profile_score"].mean()
)

In [48]:
# Fill the missing values in the 'hr_interview_score' column with the mean of the column
test_df["hr_interview_score"] = test_df["hr_interview_score"].fillna(
    test_df["hr_interview_score"].mean()
)

In [49]:
# Fill the missing values in the 'portfolio_score' column with the mean of the column
test_df['portfolio_score'] = test_df['portfolio_score'].fillna(
    test_df['portfolio_score'].mean()
    )

In [50]:
# Fill the missing values in the 'github_avg_stars' column with the median of the column
test_df["github_avg_stars"]= test_df["github_avg_stars"].fillna(test_df["github_avg_stars"].median())

# Fill the missing values in the 'open_source_contribution_count' column with the median of the column
test_df["open_source_contribution_count"] = test_df["open_source_contribution_count"].fillna(
    test_df["open_source_contribution_count"].median())

In [ ]:
# test_df.to_csv('data/test_preprocessed.csv', index=False)

# Model training

In [36]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [37]:
train_df = df.copy()
test_df_copy = test_df.copy()

In [38]:
test_df_copy = test_df_copy.drop(columns=["student_id", "mentor_feedback_text"])

In [39]:
train_df = train_df.drop(columns=["student_id", "mentor_feedback_text"])

In [40]:
X_train = train_df.drop(columns=["career_success_score"])
y_train = train_df["career_success_score"]

In [41]:
X_test = test_df_copy

In [42]:
# # Feature selection based on Lasso regression
# X = train_df.drop(columns=["career_success_score"])
# y = train_df["career_success_score"]

In [43]:
# X_train, X_test, y_train, y_test = train_test_split(
#     X, y, test_size=0.2, random_state=42
# )

In [44]:
# Model1: Random Forest Regressor
rf_model = RandomForestRegressor(n_estimators=100, random_state=42, max_depth=10)
rf_model.fit(X_train, y_train)

RandomForestRegressor(max_depth=10, random_state=42)

In [45]:
rf_predictions = rf_model.predict(X_test)

In [46]:
rf_predictions

array([63.55968435, 67.11567513, 73.81688705, ..., 64.75415266,
       82.71239162, 75.33264132])

In [47]:
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

LinearRegression()

In [48]:
lr_predictions = lr_model.predict(X_test)

In [49]:
lr_predictions

array([63.55251627, 65.11578097, 69.62021604, ..., 51.69840809,
       87.02353661, 77.6989682 ])

In [50]:
output_rf = pd.DataFrame({
    "student_id": student_id,
    "career_success_score": rf_predictions
})

output_lr = pd.DataFrame({
    "student_id": student_id,
    "career_success_score": lr_predictions
})

output_rf.to_csv("rf_predictions.csv", index=False)
output_lr.to_csv("lr_predictions.csv", index=False)

# Train with selected features

In [51]:
train_df = df.copy()
test_df_copy = test_df.copy()

In [52]:
# Lasso ile seçilmiş feature listesi
selected_features = [
    "real_client_project_count",
    "cgpa",
    "hackathon_awards",
    "project_quality_score",
    "hackathon_count",
    "github_repo_count",
    "internship_duration_months",
    "technical_interview_score",
    "bootcamp_count",
    "certification_count",
    "communication_score",
    "problem_solving_score",
    "interviews_attended",
    "portfolio_score",
    "cloud_score",
    "teamwork_score",
    "coding_score",
    "github_avg_stars",
    "devops_score",
    "cv_quality_score",
    "open_source_contribution_count",
    "backend_score",
    "hr_interview_score",
    "presentation_score",
    "linkedin_profile_score",
    "leadership_score",
    "attendance_rate",
    "english_exam_score",
    "sql_score",
    "machine_learning_score",
    "applications_sent",
    "data_structures_score",
    "graduation_year",
    "target_role",
    "application_year",
    "failed_courses_count",
    "university_tier"
]

# Eğitim verisi
X_train = train_df[selected_features]
y_train = train_df["career_success_score"]

# Test verisi (target yok)
X_test = test_df[selected_features]

In [53]:
# --- Model 1: Random Forest ---
rf_model = RandomForestRegressor(
    n_estimators=200, random_state=42, max_depth=8
)
rf_model.fit(X_train, y_train)
rf_preds = rf_model.predict(X_test)

In [54]:
# --- Model 2: Linear Regression ---
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
lr_preds = lr_model.predict(X_test)

In [55]:
# --- Tahminleri CSV formatına çevir ---
output_rf = pd.DataFrame({
    "student_id": student_id,
    "career_success_score": rf_preds
})

output_lr = pd.DataFrame({
    "student_id": student_id,
    "career_success_score": lr_preds
})

# Dosyaları kaydet
output_rf.to_csv("predictions_rf.csv", index=False)
output_lr.to_csv("predictions_lr.csv", index=False)